# .simpleci.yaml
# Put this file in the ROOT of the repo you want SimpleCI to test.
# When you push to GitHub, SimpleCI will read this file and run these steps.

pipeline:
  name: SimpleCI-backend

  branches:
    - main
    - develop    # only these branches will trigger CI

  steps:
    - name: Install Dependencies
      run: cd apps/backend && npm install

    - name: Run Tests
      run: cd apps/backend && npm test

    - name: Build
      run: cd apps/backend && npm run build
